### ISSUE TITLE
Unable to install uswds-gulp without running `npm install --save del`

### ISSUE THREAD

**Issue by albertkun** [uswds/uswds-gulp#44]
This may be related to the (closed) issue #42, but `del` seems to be missing from the package.json when following the instructions to install `uswds-gulp`:

![image](https://user-images.githubusercontent.com/8574425/144323652-6d094ebb-aefe-4602-94fb-e9255ef80cb1.png)

For now I've been using the workaround `npm install --save del`, but let me know if I'm missing something.

Thank you!

**Comment by mejiaj** [comment]
Thanks for reporting this! I've created a PR #45. Would you mind testing it out?

**Comment by danizen** [comment]
I also encountered this issue. Aside from missing del, I solved all my issues mentioned in #42 by switching to yarn - it allows me to keep up with the latest audit findings easier, but I understand why GSA TTS wouldn't want to do that.  Keeping it with npm may make adoption simpler for designers who have never used SCSS before.

Consider switching to yarn so that the updates can be a little less painful over time, but I understand if you decide not.
